linters:
    enable-all: true
    disable:
        - exhaustivestruct
        - gochecknoinits
        - gochecknoglobals
        - gci
        - varnamelen
        - revive
        - exhaustruct
        - wrapcheck
        - gosec
        - durationcheck
linters-settings:
  funlen:
    lines: 70
    statements: 40